### ISSUE TITLE
A bug when running dodrio-data-gen.py

### ISSUE THREAD

**Issue by Yb-Z** [poloclub/dodrio#2]
May I ask why I encount this problem, I had no changes about the codes.

![image](https://user-images.githubusercontent.com/57145931/122190567-837f4500-cec4-11eb-9b8c-c4a578de4285.png)

**Comment by rturko3** [comment]
Hi, thanks for experimenting with customizing Dodrio!

This issue is most likely an issue with the version of the `transformers` library you are using. As you can see, the `add_pooling_layer` argument is not present in all versions of the library. ([v4.7.0](https://huggingface.co/transformers/model_doc/bert.html#bertmodel) vs. [v2.11.0](https://huggingface.co/transformers/v2.11.0/model_doc/bert.html#bertmodel)). Try changing the version of the library that you are using to see if this resolves your problems. We will upload an `environment.yml` file with all the necessary dependencies soon!

**Comment by xiaohk** [comment]
Let us know if https://github.com/poloclub/dodrio/issues/2#issuecomment-866262279 didn't fix the problem. I will close the issue now, feel free to re-open it :)
